### ISSUE TITLE
php-fpm not starting since 1.5.2-r7-fpm

### ISSUE THREAD

**Issue by waja** [instrumentisto/roundcube-docker-image#11] opened 2022-06-21 18:44 UTC
Hi,

thanks for keeping up this nice project.

With the update from `1.5.2-r6-fpm` to `1.5.2-r7-fpm` yesterday the image is running but not able to start `php-fpm`.

The process list of the container is:
```
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   17 root      0:00 {rc.init} /bin/sh -e /run/s6/basedir/scripts/rc.init top /docker-entrypoint.sh php-fpm
   18 root      0:00 s6-supervise s6-linux-init-shutdownd
   20 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   22 root      0:00 s6-rc-init -c /run/s6/db /run/service
   23 root      0:13 /package/admin/s6/command/s6-ftrigrd
   24 root      0:00 sh
   29 root      0:00 ps aux
/app #
```

Indeed, there is no log output cause `syslog` is also not running.

Here is the process list of `1.5.2-r6-fpm`:
```
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   17 root      0:00 {rc.init} /bin/sh -e /run/s6/basedir/scripts/rc.init top /docker-entrypoint.sh php-fpm
   18 root      0:00 s6-supervise s6-linux-init-shutdownd
   21 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   24 root      0:00 s6-supervise s6rc-fdholder
   25 root      0:00 s6-supervise syslog
   26 root      0:00 s6-supervise s6rc-oneshot-runner
   33 root      0:00 syslogd -n
   36 root      0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-one
   66 root      0:00 php-fpm: master process (/usr/local/etc/php-fpm.conf)
   73 www-data  0:00 php-fpm: pool www
   74 www-data  0:00 php-fpm: pool www
   75 root      0:00 sh
   81 root      0:00 ps aux
/app #
```

If there is anything I can provide to help to trace this issue down, please let me know.

Many thanks, Jan.

**Comment by tyranron** [comment] 2022-06-22 14:14
@waja this is weird... 🤔   
I cannot reproduce this. Taking the [example](https://github.com/instrumentisto/roundcube-docker-image/blob/1.5.2-r7/examples/fpm-nginx.docker-compose.yml) and adjusting it like this:
```yaml
version: '3'
services:
  roundcube:
    image: ghcr.io/instrumentisto/roundcube:1.5.2-r7-fpm
    expose:
      - "9000"
    volumes:
      - app-volume:/app
      - ./roundcube.config.php:/app/config/config.inc.php:ro
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - roundcube
    ports:
      - "80:80"
    volumes:
      - app-volume:/var/www
      - ./fpm.nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  app-volume:
```
Gives me that everyhing is OK:
```
$ docker compose -f fpm-nginx.docker-compose.yml up       
[+] Running 3/3
 ⠿ Network examples_default        Created                                                                                                    0.2s
 ⠿ Container examples-roundcube-1  Created                                                                                                    0.3s
 ⠿ Container examples-nginx-1      Created                                                                                                    0.3s
Attaching to examples-nginx-1, examples-roundcube-1
examples-roundcube-1  | s6-rc: info: service syslog: starting
examples-roundcube-1  | s6-rc: info: service s6rc-oneshot-runner: starting
examples-roundcube-1  | s6-rc: info: service syslog successfully started
examples-roundcube-1  | Jun 22 14:10:16 c0d8e2adf99b syslog.info syslogd started: BusyBox v1.35.0
examples-roundcube-1  | s6-rc: info: service s6rc-oneshot-runner successfully started
examples-roundcube-1  | s6-rc: info: service fix-attrs: starting
examples-roundcube-1  | s6-rc: info: service fix-attrs successfully started
examples-roundcube-1  | s6-rc: info: service legacy-cont-init: starting
examples-roundcube-1  | s6-rc: info: service legacy-cont-init successfully started
examples-roundcube-1  | s6-rc: info: service legacy-services: starting
examples-roundcube-1  | s6-rc: info: service legacy-services successfully started
examples-roundcube-1  | [22-Jun-2022 14:10:16] STARTUP: PHP OPcache JIT is enabled of 100M
examples-roundcube-1  | [22-Jun-2022 14:10:16 Etc/UTC] PHP Deprecated:  PHP Startup: Use of mbstring.internal_encoding is deprecated in Unknown on line 0
examples-roundcube-1  | [22-Jun-2022 14:10:17] NOTICE: fpm is running, pid 67
examples-roundcube-1  | [22-Jun-2022 14:10:17] NOTICE: ready to handle connections
examples-nginx-1      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
examples-nginx-1      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
examples-nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
examples-nginx-1      | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
examples-nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
examples-nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
examples-nginx-1      | /docker-entrypoint.sh: Configuration complete; ready for start up
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: using the "epoll" event method
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: nginx/1.22.0
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: OS: Linux 5.10.76-linuxkit
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: start worker processes
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: start worker process 24
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: start worker process 25
```
<img width="851" alt="Screenshot 2022-06-22 at 16 11 58" src="https://user-images.githubusercontent.com/7114909/175051245-fbbeddae-e31c-49a9-b2a6-9735e0c5e025.png">

**Comment by waja** [comment] 2022-06-23 04:04
My config is the following and working well with `r6` but not with `r7`:

```
networks:
  system_traefik:
    external: true
    name: system_traefik
services:
  nginx:
    depends_on:
      roundcube:
        condition: service_started
    image: nginx:stable-alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.backend: nginx
      traefik.default.protocol: http
      traefik.docker.network: system_traefik
      traefik.enable: "true"
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.entrypoints: websecure
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.middlewares: default-security-headers@file
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.rule: Host(`webmail.test.org`)
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.tls: "true"
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.tls.certresolver: default
      traefik.http.services.roundcube-nginx-itYXUrdajns5.loadbalancer.server.port: '80'
      traefik.port: '80'
    networks:
      default: {}
      system_traefik: {}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./config/fpm.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /etc/timezone:/etc/timezone:ro
    - app-volume:/var/www:rw
  roundcube:
    image: instrumentisto/roundcube:1.5-fpm
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
    - app-volume:/app:rw
    - ./config/roundcube.config.php:/app/config/config.inc.php:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/db:/var/db:rw
version: '3.7'
volumes:
  app-volume: {}
```

Looking at the config of the roundcube container, I don't see something special, which might cause the issue. But since the issue seems related to starting all the processes on container startup I would guess it might be related to https://github.com/instrumentisto/roundcube-docker-image/commit/9f8e6ea0a5aa71981d915f76cde4ebe5acb4d831?

**Comment by waja** [comment] 2022-06-23 04:39
I tried to fork this project and to revert https://github.com/instrumentisto/roundcube-docker-image/commit/9f8e6ea0a5aa71981d915f76cde4ebe5acb4d831 and let github ci do the magic ... but it seems I'm not able to understand your build matrix and get a tag make an upload to ghcr. :/

**Comment by waja** [comment] 2022-06-23 05:28
I tagged a [1.5.2-r7.1](https://github.com/waja/roundcube-docker-image/releases/tag/1.5.2-r7.1) and I hoped this gets uploaded to GHCR. The Login was successful but it seemed not uploaded. Did I miss something what's needed too for a successful upload to GHCR?

**Comment by tyranron** [comment] 2022-06-23 07:46
@waja 

> The Login was successful but it seemed not uploaded. Did I miss something what's needed too for a successful upload to GHCR?

CI pipeline uploads the built image to 3 registries simultaneously: GitHub Container Registry, Quay.io and DockerHub. First, it authenticates on them, and only later it pushes the built image to them. The [error in your CI ](https://github.com/waja/roundcube-docker-image/runs/7016926337?check_suite_focus=true) states that authentication to Quay.io failed, so pipeline failed before pushing. Remove Quay.io and DockerHub authorization and redact `Makefile` to contain only `NAMESPACES := ghcr.io/waja` and replace any `instrumentisto` phrases with `waja`. This should work.

**Comment by tyranron** [comment] 2022-06-23 07:55
@waja I've pushed https://github.com/instrumentisto/roundcube-docker-image/commit/c73483e84bbb835ccb6169f1f00d67c125ae2243 to make things easier in `Makefile`. Now you only need to set `OWNER := waja` and `NAMESPACES := ghcr.io/$(OWNER)` in `# Project parameters #` section.

**Comment by tyranron** [comment] 2022-06-23 07:58
@waja 

> But since the issue seems related to starting all the processes on container startup I would guess it might be related to [9f8e6ea](https://github.com/instrumentisto/roundcube-docker-image/commit/9f8e6ea0a5aa71981d915f76cde4ebe5acb4d831)?

Indeed. Could you show the initial log of `docker-compose up`?

**Comment by waja** [comment] 2022-06-23 08:11
> Indeed. Could you show the initial log of `docker-compose up`?

it does NOT contain anything of the php-fpm container, just from the nginx.

But as you requested:

```
nginx_1      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1      | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
nginx_1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1      | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: using the "epoll" event method
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: nginx/1.22.0
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: OS: Linux 4.19.0-20-amd64
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: start worker processes
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: start worker process 22
nginx_1      | 2022/06/23 10:09:48 [notice] 1#1: start worker process 23
nginx_1      | 2022/06/23 10:09:52 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.4, server: , request: "POST /?_task=mail&_action=refresh HTTP/1.1", upstream: "fastcgi://192.168.112.2:9000", host: "webmail.test.org", referrer: "https://webmail.test.org/?_task=mail&_mbox=INBOX"
```

**Comment by waja** [comment] 2022-06-23 08:15
> @waja I've pushed [c73483e](https://github.com/instrumentisto/roundcube-docker-image/commit/c73483e84bbb835ccb6169f1f00d67c125ae2243) to make things easier in `Makefile`. Now you only need to set `OWNER := waja` and `NAMESPACES := ghcr.io/$(OWNER)` in `# Project parameters #` section.

If your OWNER string is equivalent to your Github username, you can also use `OWNER=${GITHUB_ACTOR}`.

**Comment by tyranron** [comment] 2022-06-23 09:58
@waja 

> it does NOT contain anything of the php-fpm container, just from the nginx.

Weird. Does it reproduce on the my example above? Could you check?

> If your OWNER string is equivalent to your Github username, you can also use `OWNER=${GITHUB_ACTOR}`.

Neat, but `GITHUB_REPOSITORY_OWNER` seems to be more proper here. So the `OWNER := $(or $(GITHUB_REPOSITORY_OWNER),waja)` would be the best solution. 👍

**Comment by waja** [comment] 2022-06-23 12:41
The point is ... I've another instance running with essentially the same setup as the broken one and that is working well. 

Anyway ... I managed to get [1.5.2-r7.1](https://github.com/waja/roundcube-docker-image/tree/1.5.2-r7.1) build and uploaded [here](https://github.com/waja/roundcube-docker-image/pkgs/container/roundcube/26461810?tag=1.5.2-r7.1-fpm) and this is running well ... it is basically reverted https://github.com/instrumentisto/roundcube-docker-image/commit/9f8e6ea0a5aa71981d915f76cde4ebe5acb4d831 and the other commits was just to get it build (in some way) [maybe here is room for improvements on your end to just get that stuff running and uploaded in the own ghcr space but not on docker and qualy, which makes debugging easier, if you have some spare time].

So it seems s6 related. I would like debug a bit further, but I have to break production of this instance all the time. When I did this in the evening, I was unable to debug further cause there was no syslog available and inside the container I also did not found something that enlighted me in some way. Any suggestion what I can do to tackle the issue down?

**Comment by tyranron** [comment] 2022-06-23 13:16
@waja well if this reproduces on one machine, but doesn't on another, then it may be caused by two reasons (cannot figure out other):
- either you have specific arch on that machine and `s6` has troubles with it;
- or you have outdated Linux kernel on that machine that `s6` breaks on.

**Comment by tyranron** [comment] 2022-06-23 13:20
Marking this as `wontfix` as it's unlikely can be fixed on our side. I leave this issue opened for a while, so @waja may describe the cause once he investigates it.

**Comment by waja** [comment] 2022-06-23 13:52
Okay ... It seems that s6 3.1.1.0 introduced incompatibility with (Debian) Kernel 4.19.0(-20-amd64), booting into 5.10.0(-0) fixed the issue.

**Closed as completed** 2022-06-23 13:54 UTC
Labels: bug

**Comment by waja** [comment] 2022-06-23 14:02
@tyranron many thanks for pointing me to the kernel issue.

**Comment by tyranron** [comment] 2022-06-24 08:46
@waja see also:
- https://github.com/just-containers/s6-overlay/releases/tag/v3.1.1.1
- https://github.com/instrumentisto/roundcube-docker-image/releases/tag/1.5.2-r8
